name: Learn-You-a-Haskell-for-Great-Good
version: 0.1.0.0
github: "dzylikecode/lang-hs"
license: BSD3
author: "Dz"
maintainer: "MathBeWithCode@gmail.com"
copyright: "Copyright (c) 2022 Dz"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/dzylikecode/test-snake#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  singleFile:
    source-dirs: modules/singleFile
    main: main.hs
    other-modules: Geometry
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  multiFile:
    source-dirs: modules/multiFile
    main: main.hs
    other-modules:
      - GeometryM.Cube
      - GeometryM.Cuboid
      - GeometryM.Sphere
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
  queryAvailableLocker:
    source-dirs: Making-Our-Own-Types-and-Typeclasses/queryAvailableLocker
    main: main.hs
    # other-extensions:
    #   - ImportQualifiedPost
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - containers
  todo:
    source-dirs: Input-and-Output/todo
    main: main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - directory

internal-libraries:
  Geometry-SingleFile:
    source-dirs: modules/singleFile
    exposed-modules:
      - Geometry
    other-modules: []
  Geometry-multiFile:
    source-dirs: modules/multiFile
    exposed-modules:
      - GeometryM.Cube
      - GeometryM.Cuboid
      - GeometryM.Sphere
    other-modules: []
